# Generated by Django 3.0.8 on 2020-07-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user',
            new_name='User',
        ),
    ]
